#ifndef SUBROUTINES_H
#define SUBROUTINES_H

#include <set>  // used in Merge Clusters routine
#include "simulationcell.h"

using namespace std;





/****************************************************************************************************
* get the effective field generated by neighbouring spins (up to J constant)
 ****************************************************************************************************/
int GetEffectiveField(SimulationCell& SC, int ispin){
    int field = 0; 
    for (auto jspin =SC.GetLattice().at(ispin).begin(); 
              jspin!=SC.GetLattice().at(ispin).end(); 
              jspin++)
        field += SC.GetSpins().Get(*jspin);
     
    return field;  
}

/****************************************************************************************************
* get the total energy (up to J constant)
 ****************************************************************************************************/
int GetEnergy(SimulationCell& SC){
    int energy = 0; 

    int istate = 0;
    for (int ispin=0; ispin!=SC.GetSize(); ispin++){
        istate = SC.GetSpins().Get(ispin);
        for (auto jspin =SC.GetLattice().at(ispin).begin(); 
                  jspin!=SC.GetLattice().at(ispin).end(); 
                  jspin++)
            energy += istate*SC.GetSpins().Get(*jspin);
    } 
    return (int) energy/2; // divide by 2 to compensate for the double counting  
}
#endif
